### ISSUE TITLE
Fix command on README.md

### ISSUE THREAD

**Issue by hxiong388** [GoogleCloudPlatform/google-cloud-gemserver#17]
s/google-cloud-gemserver create-key/google-cloud-gemserver create_key/ in [README.md](https://github.com/GoogleCloudPlatform/google-cloud-gemserver/blame/master/README.md#L98)

**Comment by dazuma** [comment]
We probably should prefer "create-key" unless Thor doesn't like it.

**Comment by arhamahmed** [comment]
Experimentally, it seems multi-word commands in Thor work with both `_` and `-`. Since `-` is more common, I can update the docs to use `-` everywhere.

**Comment by hxiong388** [comment]
That works good. Just make sure the commands are consistent on README.
