### ISSUE TITLE
Verify server accessibility after GAE deployment

### ISSUE THREAD

**Issue by hxiong388** [GoogleCloudPlatform/google-cloud-gemserver#18]
GAE deployment is flaky and service may not be accessible right after deployment. When I ran `google-cloud-gemserver create`, it creates a key for me right after deployment, but the key looks like this:
```sh
$ cat ~/.gem/credentials
:master-gemserver-key:  Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>
```

The gem should
1. Verify GAE deployment is accessible before proceeding with other commands.
2. Verify key is valid before setting it into `~/.gem/credentials` file.

**Comment by dazuma** [comment]
You might consider verifying several times over some short length of time (maybe 10-20 seconds) to see if it comes alive in that time, before giving up.
